image: ubuntu
build_script:
 - echo building...

 - mv $RESOURCE/qufop .
 - mv $RESOURCE/qufop.conf .
 - mv $RESOURCE/roundpic.conf .
 - mv $RESOURCE/ufop.yaml .

 - sudo apt-get -y install libmagickwand-dev

run: ./qufop qufop.conf