image: ubuntu
build_script:
 - echo building...
 - sudo mv $RESOURCE/bin/ffmpeg /usr/local/bin/
 - sudo mv $RESOURCE/lib/* /lib/x86_64-linux-gnu/
 - mv $RESOURCE/qufop .
 - mv $RESOURCE/amerge.conf .
 - mv $RESOURCE/qufop.conf .
 - mv $RESOURCE/ufop.yaml .
run: ./qufop qufop.conf